fix the git yml

diff --git a/.github/workflows/automate_deploy.yaml b/.github/workflows/automate_deploy.yaml
--- a/.github/workflows/automate_deploy.yaml
+++ b/.github/workflows/automate_deploy.yaml
@@ -7,35 +7,28 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
+
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: pull latest code
-      run: |
-          echo "Take the pull "
-          git pull origin main || { echo "Git pull failed"; exit 1; }
+      - name: Pull latest code
+        run: git pull origin main || { echo "Git pull failed"; exit 1; }
 
-    - name: Set environment variables from GitHub Secrets
-        run: |
-          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}"
-          export DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
-          export DB_NAME=${{ secrets.DB_NAME }}
-          export DB_USER=${{ secrets.DB_USER }}
-          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
-          export DB_HOST=${{ secrets.DB_HOST }}
-          export DB_PORT=${{ secrets.DB_PORT }}
+      - name: Set environment variables from GitHub Secrets
+        env:
+          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
+          DB_NAME: ${{ secrets.DB_NAME }}
+          DB_USER: ${{ secrets.DB_USER }}
+          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+          DB_HOST: ${{ secrets.DB_HOST }}
+          DB_PORT: ${{ secrets.DB_PORT }}
         run: echo "Environment variables set successfully"
 
-    - name : run docker
-      run: |
-        echo "Docker build"
-        docker compose build --no-cache|| { echo "docker failed"; exit 2; }
+      - name: Run Docker
+        run: |
+          echo "Docker build"
+          docker compose build --no-cache || { echo "docker failed"; exit 2; }
 
-        echo "Docker run in background"
-        docker compose up -d|| { echo "docker failed background"; exit 3; }
-        
-
-      
-
-
+          echo "Docker run in background"
+          docker compose up -d || { echo "docker failed background"; exit 3; }
