fix the git yml

diff --git a/.github/workflows/automate_deploy.yaml b/.github/workflows/automate_deploy.yaml
--- a/.github/workflows/automate_deploy.yaml
+++ b/.github/workflows/automate_deploy.yaml
@@ -52,15 +52,15 @@ jobs:
 
 
 
-      # - name: Pull latest code
-      #   run: git pull origin main || { echo "Git pull failed"; exit 1; }
+      - name: Pull latest code
+        run: git pull origin main || { echo "Git pull failed"; exit 1; }
 
 
 
-      # - name: Run Docker
-      #   run: |
-      #     echo "Docker build"
-      #     docker compose build --no-cache || { echo "docker failed"; exit 2; }
+      - name: Run Docker
+        run: |
+          echo "Docker build"
+          docker compose build --no-cache || { echo "docker failed"; exit 2; }
 
-      #     echo "Docker run in background"
-      #     docker compose up -d || { echo "docker failed background"; exit 3; }
+          echo "Docker run in background"
+          docker compose up -d || { echo "docker failed background"; exit 3; }
